### ISSUE TITLE
Pre-Beta release checklist

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#115]
- [x] q2 plugin for regression
- [x] radialplot
- [x] heatmap
- [x] q2 plugin for clustering (#116)
- [x] q2 plugin for visualizations (#118, #119, #120)
- [x] remove required dependency to ete3
- [x] update notebooks
- [x] ship off notebooks to binder
- [x] check headers for copyright
- [x] check toctrees
- [x] change version numbers
- [x] update changelog
- [x] cut and tag release
- [x] upload to conda
