### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by mortonjt** [biocore/gneiss#264]
- [ ] Add more details about the balance_boxplot in the header: https://github.com/biocore/gneiss/blob/master/gneiss/plot/_decompose.py#L18
- [ ] Add more details about the proportion plot: https://github.com/biocore/gneiss/blob/master/gneiss/plot/_decompose.py#L82  
- [ ] Make note of recursion stack limit in radialplot: https://github.com/biocore/gneiss/blob/master/gneiss/plot/_radial.py#L16 https://github.com/biocore/gneiss/blob/master/gneiss/plot/_radial.py#L16
- [ ] Add docs for ilr transform (also specify that no zeros are allowed): https://github.com/biocore/gneiss/blob/master/gneiss/composition/_composition.py#L15
- [ ] Add links to patsy in q2 regression modules: https://github.com/qiime2/q2-gneiss/blob/master/q2_gneiss/regression/_regression.py#L53 https://github.com/qiime2/q2-gneiss/blob/master/q2_gneiss/regression/_regression.py#L93
- [ ] Update the newest docs.  This will require updating the sphinx docs and pushing against master: https://github.com/biocore/gneiss/issues/252

Bonus Features
- [ ] Allow for the ilr transform to return a tree and perform the bifurcate and rename_internal_nodes commands before returning the tree.  In addition, add an optional pseudocount parameter so we can remove the add-pseudocount option in q2-gneiss.  In addition, this will be critical for enabling phylogenetic tree handling. 
 Will require modifications to both here https://github.com/biocore/gneiss/blob/master/gneiss/composition/_composition.py#L15  and here https://github.com/qiime2/q2-gneiss/blob/master/q2_gneiss/composition/_composition.py
